[package]
name = "rust_settler"
version = "0.1.0"
authors = ["niels <highintothesky@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rust_settler"
path = "main.rs"
